apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
    os: linux
    lang: node
spec:
  containers:
  - name: hello-container
    image: linkclean/hello
    ports:
      - containerPort: 8000