server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Desktop/Linux/work/demo_git/tmax-msa/git-local-repo
        git:
          uri: https://github.com/SecretFr/ecommerce
          #uri: file:///Users/daramg/Desktop/Linux/work/demo_git/tmax-msa/git-local-repo
          #username: linkclean@naver.com
          #password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: tmax2021
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh, refresh, metrics
