server:
  port: 0

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true
#    database: h2
  datasource:
    url: jdbc:mariadb://localhost:3306/bookdb
#    url: jdbc:mariadb://mariadb:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1234
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.example.catalogservice: DEBUG